- name: run local terraform
  hosts: localhost
  tasks:
    - name: Run terraform
      terraform:
        project_path: "./tf"
        force_init: yes
        state: present
      register: trfrm

    - name: Add tg host
      add_host:
        name: docker_server
        groups: nodes
        ansible_host: "{{ trfrm.outputs.servers.value.docker_server}}"
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Get secrets from vault
  hosts: localhost
  tasks:
    - name: Get db secrets from vault
      community.hashi_vault.vault_kv2_get:
        path: db
      register: db

    - name: Get bot secrets from vault
      community.hashi_vault.vault_kv2_get:
        path: bot
      register: bot

- name: Modify properties of the db
  hosts: localhost
  tasks:
    - name: Modify compose file from template
      ansible.builtin.template:
        src: "{{ compose_file }}"
        dest: "{{ compose_file | regex_replace('j2$', 'yaml') }}"

    - name: Modify docker conf from template
      ansible.builtin.template:
        src: "{{ daemon_conf }}"
        dest: "{{ daemon_conf | regex_replace('j2$', 'json') }}"

- name: Wait timeout for creating instances
  hosts: localhost
  connection: local

  tasks:
    - name: Wait for db port 22
      wait_for:
        host: "{{ trfrm.outputs.servers.value.docker_server}}"
        port: 22

- hosts: docker_server
  name: Deploy application with docker
  become: yes
  vars:
    compose_yaml: "{{ compose_file | regex_replace('j2$', 'yaml') }}"
    daemon_json: "{{ daemon_conf | regex_replace('j2$', 'json') }}"
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Add key GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add The Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Docker Installation
      apt:
        name: docker-ce
        state: present

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present

    - name: Install docker compose pip
      apt:
        name: docker-compose
        state: present

    - name: Copy directory project
      copy:
        src: "{{ daemon_json }}"
        dest: /etc/docker

    - name: Restart Docker service
      community.docker.docker_service:
        state: restarted

    - name: Ensure the project directory exists
      ansible.builtin.file:
        path: /home/ubuntu/project  
        state: directory

    - name: Copy directory project
      copy:
        src: "{{ compose_yaml }}"
        dest: /home/ubuntu/project

    - name: Start docker containers
      docker_compose:
        project_src: project/
