- name: Modify properties of the db
  hosts: localhost
  tasks:
    - name: Get db secrets from vault
      community.hashi_vault.vault_kv2_get:
        path: db
      register: db
      
    - name: Modify sql init file from template
      ansible.builtin.template:
        src: "{{ sql_init_file }}"
        dest: "{{ sql_init_file | regex_replace('j2$', 'sql') }}"

    - name: Modify compose file from template
      ansible.builtin.template:
        src: "{{ compose_file }}"
        dest: "{{ compose_file | regex_replace('j2$', 'yaml') }}"
