- name: Modify properties of the db
  hosts: localhost
  tasks:
    - name: Get db secrets from vault
      community.hashi_vault.vault_kv2_get:
        path: db
      register: db

    - name: Get db secrets from vault
      community.hashi_vault.vault_kv2_get:
        path: bot
      register: bot

    - name: Modify deployment file from template
      ansible.builtin.template:
        src: "{{ deployment_file }}"
        dest: "{{ deployment_file | regex_replace('j2$', 'yaml') }}"
