version: "3.9"
services:

  gateway_api:
    build:
      context: GatewayAPI
      dockerfile: Dockerfile
    container_name: gateway_api
    ports:
      - "8080:8080"
    environment:
      SERVICE_USERS_HOST: http://user_service:8081
      SERVICE_RESTAURANTS_HOST: http://user_service:8082
      SERVICE_RATING_HOST: http://user_service:8083

  db_service:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: db_service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  user_service:
    build:
      context: UserService
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_service:5432/users
      SPRING_DATASOURCE_USERNAME: users_user
      SPRING_DATASOURCE_PASSWORD: users_user

  restaurant_service:
    build:
      context: RestaurantService
      dockerfile: Dockerfile
    container_name: restaurant_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_service:5432/restaurants
      SPRING_DATASOURCE_USERNAME: restaurants_user
      SPRING_DATASOURCE_PASSWORD: restaurants_user

  rating_service:
    build:
      context: RatingService
      dockerfile: Dockerfile
    container_name: rating_service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rating_db:5432/comments
      SPRING_DATASOURCE_USERNAME: rating_user
      SPRING_DATASOURCE_PASSWORD: _dbpassword

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

