version: "3.9"
services:

  gateway_api:
    build:
      context: GatewayAPI
      dockerfile: Dockerfile
    container_name: gateway_api
    ports:
      - "8080:8080"
    environment:
      SERVICE_USERS_HOST: http://user:8081
      SERVICE_RESTAURANTS_HOST: http://restaurant:8082
      SERVICE_RATING_HOST: http://rating:8083
      BOT_TOKEN: _token

  dbservice:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: db_service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  user:
    build:
      context: UserService
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbservice:5432/users
      SPRING_DATASOURCE_USERNAME: _users_user
      SPRING_DATASOURCE_PASSWORD: _users_user

  restaurant:
    build:
      context: RestaurantService
      dockerfile: Dockerfile
    container_name: restaurant_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbservice:5432/restaurants
      SPRING_DATASOURCE_USERNAME: _restaurants_user
      SPRING_DATASOURCE_PASSWORD: _restaurants_user

  rating:
    build:
      context: RatingService
      dockerfile: Dockerfile
    container_name: rating_service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbservice:5432/comments
      SPRING_DATASOURCE_USERNAME: _rating_user
      SPRING_DATASOURCE_PASSWORD: _rating_user

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

