version: "3.9"
services:
  postgres:
    image: postgres:14.11
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurants
      SPRING_DATASOURCE_USERNAME: _dbname
      SPRING_DATASOURCE_PASSWORD: _dbpassword
